repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black"]
  - repo: https://github.com/grantjenks/blue
    # This is black, but with minor changes (single quotes!)
    rev: v0.9.0
    hooks:
      - id: blue
        additional_dependencies: ['flake8 < 5']  # Incompatibility
        args: ['--line-length', '88']
  - repo: https://github.com/csachs/pyproject-flake8
    rev: v0.0.1a4
    hooks:
      - id: pyproject-flake8
        name: flake8
        additional_dependencies: [
          'flake8 < 5',
          'flake8-docstrings',
          'flake8-rst-docstrings',
          'flake8-2020',
          'flake8-alfred',
          'flake8-broken-line',
          'flake8-bugbear',
          'flake8-builtins',
          'flake8-debugger',
          'flake8-noqa',
          'flake8-pep3101',
          'flake8-pie',
          'flake8-pytest',
          'flake8-pytest-style',
          'flake8-simplify',
          'pep8-naming',
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    - id: mypy
      args: ['--config-file', 'pyproject.toml']
      additional_dependencies: [
        'types-requests',
        'web3',
      ]
      # files: matic
